Repository codesquad-member-2020/issue-tracker-01, pull requests merged in 2020-06, with the labels that each got.

#3 [#1] PR Template과 Issue Template 생성
  .github/ISSUE_TEMPLATE/-be--title.md
  .github/ISSUE_TEMPLATE/-fe--title.md
  .github/ISSUE_TEMPLATE/-team--title.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚡️ Simple, 📝 Docs, 🥺 Review Needed, 🧑‍🤝‍🧑 Team

#10 [BE-#8] feat: 스프링 프로젝트 초기화
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/kr/codesquad/issuetracker/IssueTrackerApplication.java
  BE/src/main/resources/application.properties
  BE/src/test/java/kr/codesquad/issuetracker/IssueTrackerApplicationTests.java
Labels: 🚌 BE, 🥺 Review Needed

#12 BE-#8 feat: 스프링 프로젝트 초기화
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/kr/codesquad/issuetracker/IssueTrackerApplication.java
  BE/src/main/resources/application.properties
  BE/src/test/java/kr/codesquad/issuetracker/IssueTrackerApplicationTests.java
Labels: 🚌 BE, 🥺 Review Needed

#22 [FE-#5] 초기 개발환경 set-up
  FE/.gitignore
  FE/babel.config.js
  FE/package.json
  FE/public/favicon.svg
  FE/public/index.html
  FE/src/App.jsx
  FE/src/index.jsx
  FE/webpack.common.js
  FE/webpack.config.js
  FE/webpack.dev.js
  FE/webpack.prod.js
  FE/yarn.lock
Labels: 🦄 FE

#30 [BE-#18] Phase1 Mock API 개발
  BE/src/main/java/kr/codesquad/issuetracker/common/config/JacksonConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/common/config/SpringFoxConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/request/IssuesOpenStatusChangeRequest.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/IssueResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/JobResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/User.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/request/IssuesOpenStatusChangeRequestTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/response/IssueResponseTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/response/JobResponseTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/IssueTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/LabelTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/MilestoneTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/UserTest.java
Labels: 🆙 enhancement, 🚌 BE, 🥺 Review Needed

#31 백엔드 Mock API 생성 반영
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/kr/codesquad/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/kr/codesquad/issuetracker/common/config/JacksonConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/common/config/SpringFoxConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/request/IssuesOpenStatusChangeRequest.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/IssueResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/JobResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/User.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/main/resources/application.properties
  BE/src/test/java/kr/codesquad/issuetracker/IssueTrackerApplicationTests.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/request/IssuesOpenStatusChangeRequestTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/response/IssueResponseTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/response/JobResponseTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/IssueTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/LabelTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/MilestoneTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/UserTest.java
Labels: ⚡️ Simple, 🆙 enhancement, 🚌 BE

#33 [Team-#28] fix: Pull Request 템플릿에 필요없는 부분 제거
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚡️ Simple, 🐛 Bug, 🧑‍🤝‍🧑 Team

#27 Team-#19 README.md 단장하기
  README.md
Labels: 👥 논의필요, 📝 Docs, 🧑‍🤝‍🧑 Team

#43 [BE-#41] 테스트시 8080포트 사용중이라 안되는 오류 수정
  BE/src/test/resources/application.properties
Labels: ⚡️ Simple, 🐛 Bug, 🚌 BE

#44 [BE-#42] README.md에 BE 빌드상태 표시 뱃지 추가
  README.md
Labels: ⚡️ Simple, 📝 Docs, 🚌 BE

#45 [Deploy] 1주차 배포
  BE/src/test/resources/application.properties
  README.md
Labels: ⚡️ Simple, 🐛 Bug, 📝 Docs, 🚌 BE

#46 BE-#9 chore: AWS CodeDeploy를 사용하기 위한 설정 추가
  BE/appspec.yml
  BE/deploy.sh
Labels: ⚡️ Simple, 🚌 BE

#47 [Deploy] AWS CodeDeploy를 사용하기 위한 설정 추가
  BE/appspec.yml
  BE/deploy.sh
Labels: ⚡️ Simple, 🚀 Deploy, 🚌 BE

#34 [BE-#13] OAuth 인증 관련 기능 개발
  .idea/workspace.xml
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/kr/codesquad/issuetracker/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/BusinessException.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/EntityNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/ErrorCode.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/LoginRequiredException.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/UserNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubKey.java
  BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubPayload.java
  BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubToken.java
  BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubUser.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/IssueResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/dto/UserDTO.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/User.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/JwtService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
  BE/src/main/resources/application.properties
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/response/IssueResponseTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/IssueTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/LabelTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/MilestoneTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/UserTest.java
Labels: 🆙 enhancement, 🚌 BE

#50 [Deploy] Github OAuth API 개발
  .idea/workspace.xml
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/kr/codesquad/issuetracker/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/BusinessException.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/EntityNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/ErrorCode.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/LoginRequiredException.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/UserNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubKey.java
  BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubPayload.java
  BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubToken.java
  BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubUser.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/IssueResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/dto/UserDTO.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/User.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/JwtService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
  BE/src/main/resources/application.properties
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/response/IssueResponseTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/IssueTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/LabelTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/MilestoneTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/UserTest.java
Labels: 🚀 Deploy, 🚌 BE

#53 Feature/be #48
  BE/build.gradle
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/MilestoneTest.java
Labels: ✏️ Study, 📝 Docs, 🚌 BE, 🥺 Review Needed

#54 [Deploy] apply #48 Issue
  BE/build.gradle
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/MilestoneTest.java
Labels: 📝 Docs, 🚀 Deploy, 🚌 BE

#56 Fix: dev 브랜치 머지 후 코드가 정상 동작하지 않는 오류 수정
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/Issue.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/MilestoneTest.java
Labels: ⚡️ Simple, 🐛 Bug, 🚌 BE

#57 [Hotfix] [Deploy] 테스트를 통과하지 못하는 현상 수정
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/Issue.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/MilestoneTest.java
Labels: ⚡️ Simple, 🐛 Bug, 🚀 Deploy, 🚌 BE

#59 DDL 쿼리 버전관리를 합니다.
  BE/db-schema.sql
Labels: ⚡️ Simple, 📝 Docs, 🚌 BE

#51 [BE-review 요청] 1주차 리뷰요청입니다!
  .github/PULL_REQUEST_TEMPLATE.md
  .idea/workspace.xml
  BE/.gitignore
  BE/appspec.yml
  BE/build.gradle
  BE/deploy.sh
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/kr/codesquad/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/kr/codesquad/issuetracker/common/config/JacksonConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/common/config/SpringFoxConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/BusinessException.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/EntityNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/ErrorCode.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/LoginRequiredException.java
  BE/src/main/java/kr/codesquad/issuetracker/common/exception/UserNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubKey.java
  BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubPayload.java
  BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubToken.java
  BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubUser.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/request/IssuesOpenStatusChangeRequest.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/IssueResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/JobResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/dto/UserDTO.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/entity/User.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/JwtService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
  BE/src/main/resources/application.properties
  BE/src/test/java/kr/codesquad/issuetracker/IssueTrackerApplicationTests.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/request/IssuesOpenStatusChangeRequestTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/response/IssueResponseTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/response/JobResponseTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/IssueTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/LabelTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/MilestoneTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/entity/UserTest.java
  BE/src/test/resources/application.properties
  README.md
Labels: be-review

#63 BE-#62 테스트 코드 작성
  BE/build.gradle
  BE/src/main/java/kr/codesquad/issuetracker/common/error/ErrorResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/IssueResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/comment/Image.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/IssueOfIssueList.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/IssueRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/LabelOfIssue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/MilestoneOfIssue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/relation/IssueAssignee.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/relation/IssueLabel.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/User.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/UserDTO.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/UserOfIssue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/UserRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/JwtService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/LoginControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/request/IssuesOpenStatusChangeRequestTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/response/IssueResponseTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/response/JobResponseTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/comment/CommentTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/comment/ImageTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/issue/IssueOfIssueListTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/issue/IssueRepositoryTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/issue/IssueTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/label/LabelTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/milestone/MilestoneTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/relation/IssueAssigneeTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/relation/IssueLabelTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/user/UserDTOTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/user/UserRepositoryTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/user/UserTest.java
  BE/src/test/resources/application.properties
  BE/src/test/resources/data.sql
Labels: ✏️ Study, 🆙 enhancement, 🚌 BE

#64 2주차 코드 개선
  BE/build.gradle
  BE/src/main/java/kr/codesquad/issuetracker/common/error/ErrorResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/IssueResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/comment/Image.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/IssueOfIssueList.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/IssueRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/LabelOfIssue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/MilestoneOfIssue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/relation/IssueAssignee.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/relation/IssueLabel.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/User.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/UserDTO.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/UserOfIssue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/UserRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/JwtService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/LoginControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/request/IssuesOpenStatusChangeRequestTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/response/IssueResponseTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/response/JobResponseTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/comment/CommentTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/comment/ImageTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/issue/IssueOfIssueListTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/issue/IssueRepositoryTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/issue/IssueTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/label/LabelTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/milestone/MilestoneTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/relation/IssueAssigneeTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/relation/IssueLabelTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/user/UserDTOTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/user/UserRepositoryTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/user/UserTest.java
  BE/src/test/resources/application.properties
  BE/src/test/resources/data.sql
Labels: 🚌 BE

#81 BE-#75 feat: label 생성 API 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/request/LabelCreateRequest.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/LabelRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
Labels: ⚡️ Simple, 🆙 enhancement, 🚌 BE

#82 BE-#67 label 목록 조회 API 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/LabelListResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/SearchFilterLabelResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/LabelOfFilter.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/LabelOfLabelList.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/LabelRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
Labels: ⚡️ Simple, 🚌 BE

#83 BE-#66 유저 필터 목록 API 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/SearchFilterUserResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/UserOfFilter.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/UserRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/UserService.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
Labels: ⚡️ Simple, 🆙 enhancement, 🚌 BE

#85 [BE-#76] Label 수정, 삭제 API 구현
  BE/src/main/java/kr/codesquad/issuetracker/common/error/ErrorCode.java
  BE/src/main/java/kr/codesquad/issuetracker/common/error/exception/domain/label/LabelNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/request/LabelRequest.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/LabelRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
Labels: 🚌 BE

#86 [BE-#77] Milestone 추가, 수정, 삭제 API 구현
  BE/src/main/java/kr/codesquad/issuetracker/common/error/ErrorCode.java
  BE/src/main/java/kr/codesquad/issuetracker/common/error/exception/domain/milestone/MilestoneNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/MilestoneController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/request/MilestoneRequest.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/MilestoneRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MilestoneService.java
Labels: ⚡️ Simple, 🚌 BE

#87 [BE-#68] milestone 목록 API 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/MilestoneController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/MilestoneListResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/SearchFilterMilestoneResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/LabelRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/MilestoneOfFilter.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/MilestoneOfMilestoneList.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/MilestoneRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MilestoneService.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
Labels: ⚡️ Simple, 🆙 enhancement, 🚌 BE

#89 [BE-#70] Issue 생성 API 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/request/IssueCreateRequest.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/IssueRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/relation/IssueAssignee.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/relation/IssueLabel.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/UserRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
Labels: 🆙 enhancement, 🚌 BE

#90 [BE-#71] Issue 상세조회 API 개발
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/response/IssueDetail.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/comment/CommentOfIssue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/comment/ImageOfComment.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
Labels: ⚡️ Simple, 🆙 enhancement, 🚌 BE

#91 [BE-#72] Issue 정보 수정 API 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/request/IssueUpdateRequest.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
Labels: ⚡️ Simple, 🆙 enhancement, 🚌 BE

#93 BE-#73 feat: Comment 추가 API 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/request/CommentRequest.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
Labels: ⚡️ Simple, 🆙 enhancement, 🚌 BE

#94 [BE-#74] Comment 수정 API 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/IssueRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
Labels: ⚡️ Simple, 🆙 enhancement, 🚌 BE

#95 [BE-#92] Issue, Milestone open/close API 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/MilestoneController.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MilestoneService.java
Labels: 🆙 enhancement, 🚌 BE

#97 [BE-#96] Auth 인터셉터 추가 및 하드코딩으로 유저정보 넣는 부분 모두 변경
  BE/src/main/java/kr/codesquad/issuetracker/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/common/error/GlobalRestExceptionHandler.java
  BE/src/main/java/kr/codesquad/issuetracker/common/interceptor/AuthInterceptor.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/User.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/UserDTO.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
Labels: 🆙 enhancement, 🚌 BE

#100 [FE-#78] 로그인 페이지 구현
  BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/UserRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
  FE/index.html
Labels: ⚡️ Simple, 🚌 BE, 🦄 FE
