Repository codesquad-member-2020/issue-tracker-01, pull requests merged in 2020-07, with the labels that each got.

#102 [BE-#101] fix: User 클래스에서 발생하는 순환참조 문제 수정
  BE/src/main/java/kr/codesquad/issuetracker/domain/user/User.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/LoginControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/user/UserDTOTest.java
Labels: ⚡️ Simple, 🐛 Bug, 🚌 BE

#104 [BE-#103] refactor: 하드코딩된 redirect url 정보 시스템 환경변수로 설정
  BE/build.gradle
  BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
  BE/src/test/java/kr/codesquad/issuetracker/domain/user/UserDTOTest.java
Labels: 🆙 enhancement, 🐛 Bug, 🚌 BE

#106 [BE-#105] 테스트 코드를 개선합니다.
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/LoginControllerTest.java
Labels: 🆙 enhancement, 🐛 Bug, 📝 Docs, 🚌 BE

#109 [BE-#108] refactor: 배포환경에 적용 가능하도록 deploy.sh 수정
  BE/deploy.sh
Labels: 🐛 Bug, 🚌 BE

#110 [Deploy] CD 기능에 문제가 있어 보완
  BE/deploy.sh
Labels: 🐛 Bug, 🚀 Deploy, 🚌 BE

#114 [BE-#113] refactor: REST Docs를 로그인 하지 않고 확인할 수 있도록 변경
  BE/src/main/java/kr/codesquad/issuetracker/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/common/interceptor/AuthInterceptor.java
Labels: 🐛 Bug, 🚌 BE

#115 [Deploy] 2020-07-04
  BE/src/main/java/kr/codesquad/issuetracker/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/common/interceptor/AuthInterceptor.java
Labels: 🐛 Bug, 🚀 Deploy, 🚌 BE

#116 [BE-#112] REST Docs 추가제공 및 변경사항 반영
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/LoginControllerTest.java
Labels: 🆙 enhancement, 📝 Docs, 🚌 BE

#117 [Deploy] 2020-07-05
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/LoginControllerTest.java
Labels: 🚀 Deploy

#118 [BE-#112]
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
Labels: 🆙 enhancement, 📝 Docs, 🚌 BE

#120 [BE-#112] Issue 생성 테스트 코드 추가 및 REST Docs 추가
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
Labels: 🆙 enhancement, 📝 Docs, 🚌 BE

#121 [Deploy] 2020-07-06
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
Labels: 📝 Docs, 🚀 Deploy, 🚌 BE

#123 [BE-#112] Label 목록 API Test 및 REST Docs를 추가합니다.
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/LabelOfLabelList.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/LabelControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/LoginControllerTest.java
Labels: 📝 Docs, 🚌 BE

#124 [Deploy] 2020-07-07
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/LabelOfLabelList.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/LabelControllerTest.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/LoginControllerTest.java
Labels: 📝 Docs, 🚀 Deploy

#125 [BE-#112] Label 생성 API 변경 및 테스트 코드 작성 및 REST Docs 제공
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/main/java/kr/codesquad/issuetracker/common/constant/CommonConstant.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/LabelControllerTest.java
Labels: 🆙 enhancement, 📝 Docs, 🚌 BE

#126 [Deploy] 2020-07-08
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/main/java/kr/codesquad/issuetracker/common/constant/CommonConstant.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/LabelControllerTest.java
Labels: 🚀 Deploy, 🚌 BE

#127 [FE] 디렉토리 구조 설계 완료
  FE/src/index.jsx
  FE/src/selectors/IssuesSelector.js
  FE/src/store/issues/issuesAction.js
  FE/src/store/issues/issuesReducer.js
  FE/src/store/labels/labelsAction.js
  FE/src/store/labels/labelsReducer.js
  FE/src/store/milestones/milestonesAction.js
  FE/src/store/milestones/milestonesReducer.js
  FE/src/store/rootReducer.js
  FE/src/store/rootStore.js
  FE/src/views/components/App.jsx
  FE/src/views/components/Router.js
  FE/src/views/pages/CreateIssuePage.jsx
  FE/src/views/pages/CreateMilestonePage.jsx
  FE/src/views/pages/EditMilestonePage.jsx
  FE/src/views/pages/IssueDetailPage.jsx
  FE/src/views/pages/IssueListPage.jsx
  FE/src/views/pages/LabelListPage.jsx
  FE/src/views/pages/Login.jsx
  FE/src/views/pages/MilestoneListPage.jsx
  FE/src/views/pages/NotFoundPage.jsx
Labels: 🦄 FE

#128 [BE-#112] Label 수정 테스트 코드 추가 및 REST Docs 추가
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/test/java/kr/codesquad/issuetracker/controller/LabelControllerTest.java
Labels: 📝 Docs, 🚌 BE

#129 [Deploy] 2020-07-09
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/test/java/kr/codesquad/issuetracker/controller/LabelControllerTest.java
Labels: 🚀 Deploy

#130 [FE] 재사용 컴포넌트 제작 완료
  FE/babel.config.js
  FE/package.json
  FE/src/styles/GlobalStyle.js
  FE/src/views/components/App.jsx
  FE/src/views/components/Router.js
  FE/src/views/components/common/Button.jsx
  FE/src/views/components/common/Dropdown.jsx
  FE/src/views/components/common/Label.jsx
  FE/src/views/components/common/NavButtons.jsx
  FE/src/views/pages/IssueListPage.jsx
  FE/webpack.common.js
  FE/webpack.prod.js
  FE/yarn.lock
Labels: 🦄 FE

#131 [FE] 1주차 작업본 PR
  FE/.gitignore
  FE/babel.config.js
  FE/package.json
  FE/public/favicon.svg
  FE/public/index.html
  FE/src/index.jsx
  FE/src/selectors/IssuesSelector.js
  FE/src/store/issues/issuesAction.js
  FE/src/store/issues/issuesReducer.js
  FE/src/store/labels/labelsAction.js
  FE/src/store/labels/labelsReducer.js
  FE/src/store/milestones/milestonesAction.js
  FE/src/store/milestones/milestonesReducer.js
  FE/src/store/rootReducer.js
  FE/src/store/rootStore.js
  FE/src/styles/GlobalStyle.js
  FE/src/views/components/App.jsx
  FE/src/views/components/Router.js
  FE/src/views/components/common/Button.jsx
  FE/src/views/components/common/Dropdown.jsx
  FE/src/views/components/common/Label.jsx
  FE/src/views/components/common/NavButtons.jsx
  FE/src/views/pages/CreateIssuePage.jsx
  FE/src/views/pages/CreateMilestonePage.jsx
  FE/src/views/pages/EditMilestonePage.jsx
  FE/src/views/pages/IssueDetailPage.jsx
  FE/src/views/pages/IssueListPage.jsx
  FE/src/views/pages/LabelListPage.jsx
  FE/src/views/pages/Login.jsx
  FE/src/views/pages/MilestoneListPage.jsx
  FE/src/views/pages/NotFoundPage.jsx
  FE/webpack.common.js
  FE/webpack.config.js
  FE/webpack.dev.js
  FE/webpack.prod.js
  FE/yarn.lock
Labels: 🦄 FE

#132 BE-#112 test: Issue 생성 테스트 코드 변경 및 테스트 코드 변경으로 인한 리팩토링
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/IssueControllerTest.java
Labels: 🚌 BE

#133 [BE-#112] REST Docs 커스텀 Snippet 적용 및 label 삭제 API 테스트 코드 및 API 문서 추가
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/test/java/kr/codesquad/issuetracker/controller/LabelControllerTest.java
  BE/src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  BE/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: 📝 Docs, 🚌 BE

#134 BE-#112 fix: intellij 오류로 인한 snippet 수정
  BE/src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  BE/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: 🐛 Bug, 🚌 BE

#135 BE-#112 docs: REST Docs 모양 개선
  BE/src/docs/asciidoc/api-docs.adoc
Labels: 📝 Docs, 🚌 BE

#138 [FE] 이슈 목록 렌더링
  FE/package.json
  FE/src/assets/github.svg
  FE/src/assets/mockIssue.js
  FE/src/styles/GlobalStyle.js
  FE/src/utils/utilFunctions.js
  FE/src/views/components/common/Button.jsx
  FE/src/views/components/common/Header.jsx
  FE/src/views/components/common/Label.jsx
  FE/src/views/components/common/NavButtons.jsx
  FE/src/views/components/issues/IssueItem.jsx
  FE/src/views/pages/IssueListPage.jsx
  FE/webpack.common.js
  FE/yarn.lock
Labels: 🦄 FE

#140 BE-#139 fix: CORS 문제 해결
  BE/src/main/java/kr/codesquad/issuetracker/common/config/WebConfig.java
Labels: 🐛 Bug, 🚌 BE

#141 [Deploy] fix CORS Error 배포
  BE/src/main/java/kr/codesquad/issuetracker/common/config/WebConfig.java
Labels: 🐛 Bug, 🚀 Deploy

#142 [BE-#139] fix: CORS 문제 해결이 안되어서 설정 추가
  BE/src/main/java/kr/codesquad/issuetracker/common/interceptor/SimpleCorsFilter.java
Labels: 🐛 Bug, 🚌 BE

#143 [Deploy] 추가로 설정 반영 이게 안되면 NginX 문제로 추정
  BE/src/main/java/kr/codesquad/issuetracker/common/interceptor/SimpleCorsFilter.java
Labels: 🐛 Bug, 🚀 Deploy

#146 [BE-#111] Login시 토큰 초기화 기능이 정상 동작하지 않는 오류 해결
  BE/src/main/java/kr/codesquad/issuetracker/common/error/GlobalRestExceptionHandler.java
  BE/src/main/java/kr/codesquad/issuetracker/common/interceptor/AuthInterceptor.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
Labels: 🐛 Bug, 🚌 BE

#147 [BE-#145] feat: OAuth 인증기능 해제
  BE/src/main/java/kr/codesquad/issuetracker/common/interceptor/AuthInterceptor.java
Labels: 🐛 Bug, 🚌 BE

#148 [FE] Label 목록 View 제작
  FE/src/assets/mockLabel.js
  FE/src/styles/GlobalStyle.js
  FE/src/views/components/Router.js
  FE/src/views/components/common/Button.jsx
  FE/src/views/components/common/Header.jsx
  FE/src/views/components/common/Label.jsx
  FE/src/views/components/common/NavButtons.jsx
  FE/src/views/components/labels/LabelEditor.jsx
  FE/src/views/components/labels/LabelItem.jsx
  FE/src/views/pages/IssueListPage.jsx
  FE/src/views/pages/LabelListPage.jsx
Labels: 🦄 FE

#149 [BE-#122] RESTful 하지 않은 항목 변경
  BE/src/main/java/kr/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/MilestoneController.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MilestoneService.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/LabelControllerTest.java
Labels: 🐛 Bug, 🚌 BE

#150 [FE] Issue 생성/상세 View 추가
  FE/src/assets/mockIssue.js
  FE/src/views/components/common/CustomizedDropdown.jsx
  FE/src/views/components/common/User.jsx
  FE/src/views/components/issues/CommentEditor.jsx
  FE/src/views/components/issues/CommentViewer.jsx
  FE/src/views/pages/CreateIssuePage.jsx
  FE/src/views/pages/IssueDetailPage.jsx
Labels: 🦄 FE

#151 [FE] Issue, Label View 제작 완료
  FE/package.json
  FE/src/assets/github.svg
  FE/src/assets/mockIssue.js
  FE/src/assets/mockLabel.js
  FE/src/hooks/useClickOutside.jsx
  FE/src/styles/GlobalStyle.js
  FE/src/utils/utilFunctions.js
  FE/src/views/components/Router.js
  FE/src/views/components/common/Button.jsx
  FE/src/views/components/common/CustomizedDropdown.jsx
  FE/src/views/components/common/Header.jsx
  FE/src/views/components/common/Label.jsx
  FE/src/views/components/common/NavButtons.jsx
  FE/src/views/components/common/User.jsx
  FE/src/views/components/issues/CommentEditor.jsx
  FE/src/views/components/issues/CommentViewer.jsx
  FE/src/views/components/issues/IssueItem.jsx
  FE/src/views/components/labels/LabelEditor.jsx
  FE/src/views/components/labels/LabelItem.jsx
  FE/src/views/pages/CreateIssuePage.jsx
  FE/src/views/pages/IssueDetailPage.jsx
  FE/src/views/pages/IssueListPage.jsx
  FE/src/views/pages/LabelListPage.jsx
  FE/webpack.common.js
  FE/yarn.lock
Labels: 🦄 FE

#154 [FE] 이슈 생성, 이슈 상세 페이지 라우팅 구현
  FE/public/index.html
  FE/src/views/components/Router.js
  FE/src/views/components/issues/IssueItem.jsx
  FE/src/views/pages/IssueDetailPage.jsx
  FE/src/views/pages/IssueListPage.jsx
Labels: 🦄 FE

#156 [BE-#122] Milestone 목록 조회 테스트 코드 작성 및 REST Docs 추가
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/MilestoneOfMilestoneList.java
  BE/src/test/java/kr/codesquad/issuetracker/controller/MilestoneControllerTest.java
Labels: 📝 Docs, 🚀 Deploy, 🚌 BE

#157 [BE-#122] milestone 생성 테스트 코드 추가 및 REST Docs 추가 등 기타 수정사항 포함
  BE/src/docs/asciidoc/api-docs.adoc
  BE/src/test/java/kr/codesquad/issuetracker/controller/MilestoneControllerTest.java
Labels: 📝 Docs, 🚀 Deploy, 🚌 BE

#158 [FE] Label 상태관리 기능 구현
  FE/package.json
  FE/src/index.jsx
  FE/src/lib/api.js
  FE/src/lib/createRequestThunk.js
  FE/src/lib/utilFunctions.js
  FE/src/store/issue/issueAction.js
  FE/src/store/issue/issueReducer.js
  FE/src/store/label/labelAction.js
  FE/src/store/label/labelReducer.js
  FE/src/store/loading/loadingAction.js
  FE/src/store/loading/loadingReducer.js
  FE/src/store/milestone/milestoneAction.js
  FE/src/store/milestone/milestoneReducer.js
  FE/src/store/milestones/milestonesAction.js
  FE/src/store/milestones/milestonesReducer.js
  FE/src/store/rootReducer.js
  FE/src/store/rootStore.js
  FE/src/views/components/common/Button.jsx
  FE/src/views/components/common/Input.jsx
  FE/src/views/components/issues/CommentViewer.jsx
  FE/src/views/components/issues/IssueItem.jsx
  FE/src/views/components/labels/LabelEditor.jsx
  FE/src/views/components/labels/LabelItem.jsx
  FE/src/views/pages/IssueDetailPage.jsx
  FE/src/views/pages/LabelListPage.jsx
  FE/webpack.common.js
  FE/yarn.lock
Labels: 🦄 FE

#159 [FE] 3주차 Label 상태관리 구현
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/kr/codesquad/issuetracker/common/interceptor/SimpleCorsFilter.java
  FE/package.json
  FE/public/index.html
  FE/src/index.jsx
  FE/src/lib/api.js
  FE/src/lib/createRequestThunk.js
  FE/src/lib/utilFunctions.js
  FE/src/store/issue/issueAction.js
  FE/src/store/issue/issueReducer.js
  FE/src/store/label/labelAction.js
  FE/src/store/label/labelReducer.js
  FE/src/store/loading/loadingAction.js
  FE/src/store/loading/loadingReducer.js
  FE/src/store/milestone/milestoneAction.js
  FE/src/store/milestone/milestoneReducer.js
  FE/src/store/milestones/milestonesAction.js
  FE/src/store/milestones/milestonesReducer.js
  FE/src/store/rootReducer.js
  FE/src/store/rootStore.js
  FE/src/views/components/Router.js
  FE/src/views/components/common/Button.jsx
  FE/src/views/components/common/Input.jsx
  FE/src/views/components/issues/CommentViewer.jsx
  FE/src/views/components/issues/IssueItem.jsx
  FE/src/views/components/labels/LabelEditor.jsx
  FE/src/views/components/labels/LabelItem.jsx
  FE/src/views/pages/IssueDetailPage.jsx
  FE/src/views/pages/IssueListPage.jsx
  FE/src/views/pages/LabelListPage.jsx
  FE/webpack.common.js
  FE/yarn.lock
Labels: 🦄 FE
